/**
 * @fileoverview This file is auto-generated by Paraglide. Do not edit manually.
 */

import * as runtime from './runtime.js';
import { get } from 'svelte/store';

/**
 * Get the language tag store (reactive)
 * @returns {import('svelte/store').Readable<import('./runtime.js').LanguageTag>}
 */
function getLanguageTagStore() {
	return runtime.languageTagStore();
}

// Global variable to track current language - will be set by components
/** @type {import('./runtime.js').LanguageTag} */
let _currentLanguageTag = 'fr';

/**
 * Set the current language tag (called by components)
 * @param {import('./runtime.js').LanguageTag} tag
 */
export function setCurrentLanguageTag(tag) {
	_currentLanguageTag = tag;
}

/**
 * Get the current language tag (reactive)
 * This function reads from the global variable set by components
 * @returns {import('./runtime.js').LanguageTag}
 */
function getLanguageTag() {
	return _currentLanguageTag;
}

/**
 * Translation function for nav_home
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag, if not provided uses global
 * @returns {string}
 */
export function nav_home(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'HOME';
	if (tag === 'fr') return 'ACCUEIL';
	return 'HOME';
}

/**
 * Translation function for nav_ourProgram
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_ourProgram(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'OUR PROGRAM';
	if (tag === 'fr') return 'NOTRE PROGRAMME';
	return 'OUR PROGRAM';
}

/**
 * Translation function for nav_ourMeets
 * @returns {string}
 */
/**
 * Translation function for nav_ourMeets
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_ourMeets(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'OUR MEETS';
	if (tag === 'fr') return 'NOS RENCONTRES';
	return 'OUR MEETS';
}

/**
 * Translation function for nav_tryouts
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_tryouts(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'TRYOUTS';
	if (tag === 'fr') return 'ESSAIS';
	return 'TRYOUTS';
}

/**
 * Translation function for nav_clubRecords
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_clubRecords(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'CLUB RECORDS';
	if (tag === 'fr') return 'RECORDS DU CLUB';
	return 'CLUB RECORDS';
}

/**
 * Translation function for nav_coaches
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_coaches(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'COACHES';
	if (tag === 'fr') return 'ENTRAÎNEURS';
	return 'COACHES';
}

/**
 * Translation function for nav_news
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_news(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'NEWS';
	if (tag === 'fr') return 'NOUVELLES';
	return 'NEWS';
}

/**
 * Translation function for nav_gallery
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_gallery(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'GALLERY';
	if (tag === 'fr') return 'GALERIE';
	return 'GALLERY';
}

/**
 * Translation function for nav_contact
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function nav_contact(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'CONTACT US';
	if (tag === 'fr') return 'NOUS CONTACTER';
	return 'CONTACT US';
}

/**
 * Translation function for topBar_phone
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function topBar_phone(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return '450-466-6563';
	if (tag === 'fr') return '450-466-6563';
	return '450-466-6563';
}

/**
 * Translation function for topBar_email
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function topBar_email(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'info@natation-samak.org';
	if (tag === 'fr') return 'info@natation-samak.org';
	return 'info@natation-samak.org';
}

/**
 * Translation function for topBar_member
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function topBar_member(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Member';
	if (tag === 'fr') return 'Membre';
	return 'Member';
}

/**
 * Translation function for hero_joinTeam
 * @returns {string}
 */
/**
 * Translation function for hero_joinTeam
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function hero_joinTeam(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return "Join the Team";
	if (tag === 'fr') return "Joindre L'Équipe";
	return "Join the Team";
}

/**
 * Translation function for mission_welcome
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_welcome(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'WELCOME TO THE DORVAL SWIM CLUB';
	if (tag === 'fr') return 'BIENVENUE AU CLUB DE NATATION DORVAL';
	return 'WELCOME TO THE DORVAL SWIM CLUB';
}

/**
 * Translation function for mission_description
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_description(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'We are a competitive swim club that trains out of the Dorval Aquatic and Sports Complex on the edge of the south shore on Montreal\'s West Island. Our vision is to create an environment where the youth of Dorval have the opportunity to strive for excellence in the sport of swimming. By building a program that promotes training excellence, sportsmanship, character and self-confidence, the athletes of the Dorval Swim Club will have the opportunity to reach their potential and compete at the highest level. Together, with the city of Dorval, the Dorval Swim Club aspires to provide the resources and knowledge needed to achieve this mandate.';
	if (tag === 'fr') return 'Nous sommes un club de natation compétitif qui s\'entraîne au Complexe aquatique et sportif de Dorval, situé sur la rive sud de l\'île de Montréal. Notre vision est de créer un environnement où les jeunes de Dorval ont l\'opportunité de viser l\'excellence dans le sport de la natation. En construisant un programme qui favorise l\'excellence en entraînement, le fair-play, le caractère et la confiance en soi, les athlètes du Club de natation Dorval auront l\'opportunité d\'atteindre leur potentiel et de compétitionner au plus haut niveau. Ensemble, avec la ville de Dorval, le Club de natation Dorval aspire à fournir les ressources et les connaissances nécessaires pour atteindre ce mandat.';
	return 'We are a competitive swim club that trains out of the Dorval Aquatic and Sports Complex on the edge of the south shore on Montreal\'s West Island. Our vision is to create an environment where the youth of Dorval have the opportunity to strive for excellence in the sport of swimming. By building a program that promotes training excellence, sportsmanship, character and self-confidence, the athletes of the Dorval Swim Club will have the opportunity to reach their potential and compete at the highest level. Together, with the city of Dorval, the Dorval Swim Club aspires to provide the resources and knowledge needed to achieve this mandate.';
}

/**
 * Translation function for mission_missionTitle
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_missionTitle(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'OUR MISSION STATEMENT';
	if (tag === 'fr') return 'NOTRE ÉNONCÉ DE MISSION';
	return 'OUR MISSION STATEMENT';
}

/**
 * Translation function for mission_mission1
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission1(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To provide the highest level of professional coaching to prepare our athletes to compete successfully at the highest levels;';
	if (tag === 'fr') return 'Fournir le plus haut niveau d\'entraînement professionnel pour préparer nos athlètes à compétitionner avec succès aux plus hauts niveaux;';
	return 'To provide the highest level of professional coaching to prepare our athletes to compete successfully at the highest levels;';
}

/**
 * Translation function for mission_mission2
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission2(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To create an atmosphere that inspires our athletes to strive for the best in training, competition, and life, through the development of work ethic, confidence, self-motivation, and self-worth;';
	if (tag === 'fr') return 'Créer une atmosphère qui inspire nos athlètes à viser le meilleur en entraînement, en compétition et dans la vie, grâce au développement de l\'éthique de travail, de la confiance, de l\'auto-motivation et de l\'estime de soi;';
	return 'To create an atmosphere that inspires our athletes to strive for the best in training, competition, and life, through the development of work ethic, confidence, self-motivation, and self-worth;';
}

/**
 * Translation function for mission_mission3
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission3(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To develop team pride and unity where every athlete becomes each other\'s motivator and each other\'s most dedicated fan;';
	if (tag === 'fr') return 'Développer la fierté et l\'unité d\'équipe où chaque athlète devient le motivateur et le fan le plus dévoué de l\'autre;';
	return 'To develop team pride and unity where every athlete becomes each other\'s motivator and each other\'s most dedicated fan;';
}

/**
 * Translation function for mission_mission4
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission4(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To instill a love for the sport of swimming by relishing the challenges sought and conquered, at all levels of the sport;';
	if (tag === 'fr') return 'Instiller un amour pour le sport de la natation en savourant les défis recherchés et conquis, à tous les niveaux du sport;';
	return 'To instill a love for the sport of swimming by relishing the challenges sought and conquered, at all levels of the sport;';
}

/**
 * Translation function for mission_mission5
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission5(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To ensure, as much as we can, that all our athletes, coaches, and volunteers are treated with respect, and that we foster an environment where no one feels left out;';
	if (tag === 'fr') return 'Assurer, autant que possible, que tous nos athlètes, entraîneurs et bénévoles sont traités avec respect, et que nous favorisons un environnement où personne ne se sent exclu;';
	return 'To ensure, as much as we can, that all our athletes, coaches, and volunteers are treated with respect, and that we foster an environment where no one feels left out;';
}

/**
 * Translation function for mission_mission6
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_mission6(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'To be an active participant within the City of Dorval community.';
	if (tag === 'fr') return 'Être un participant actif au sein de la communauté de la ville de Dorval.';
	return 'To be an active participant within the City of Dorval community.';
}

/**
 * Translation function for mission_coachesTitle
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_coachesTitle(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'OUR COACHES';
	if (tag === 'fr') return 'NOS ENTRAÎNEURS';
	return 'OUR COACHES';
}

/**
 * Translation function for mission_coaches1
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_coaches1(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Led by Head Coach Marc Daoust, our staff is committed to our Vision and Mission statements.';
	if (tag === 'fr') return 'Dirigés par l\'entraîneur-chef Marc Daoust, notre personnel est engagé envers nos énoncés de Vision et de Mission.';
	return 'Led by Head Coach Marc Daoust, our staff is committed to our Vision and Mission statements.';
}

/**
 * Translation function for mission_coaches2
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_coaches2(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'With a focus on teaching the technical aspects of swimming, as a team,';
	if (tag === 'fr') return 'Avec un accent sur l\'enseignement des aspects techniques de la natation, en équipe,';
	return 'With a focus on teaching the technical aspects of swimming, as a team,';
}

/**
 * Translation function for mission_coaches3
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function mission_coaches3(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'We are motivated to get our swimmers to be the best they can be at maturity.';
	if (tag === 'fr') return 'Nous sommes motivés à amener nos nageurs à être les meilleurs qu\'ils peuvent être à maturité.';
	return 'We are motivated to get our swimmers to be the best they can be at maturity.';
}

/**
 * Translation function for news_title
 * @returns {string}
 */
export function news_title() {
	const tag = getLanguageTag();
	if (tag === 'en') return 'New Platform';
	if (tag === 'fr') return 'Nouvelle plateforme';
	return 'New Platform';
}

/**
 * Translation function for news_date
 * @returns {string}
 */
export function news_date() {
	const tag = getLanguageTag();
	if (tag === 'en') return 'June 03 2021';
	if (tag === 'fr') return 'juin 03 2021';
	return 'June 03 2021';
}

/**
 * Translation function for news_readMore
 * @returns {string}
 */
export function news_readMore() {
	const tag = getLanguageTag();
	if (tag === 'en') return 'read more';
	if (tag === 'fr') return 'lire la suite';
	return 'read more';
}

/**
 * Translation function for news_viewAll
 * @returns {string}
 */
export function news_viewAll() {
	const tag = getLanguageTag();
	if (tag === 'en') return 'View All News';
	if (tag === 'fr') return 'Voir toutes les nouvelles';
	return 'View All News';
}

/**
 * Translation function for partners_title
 * @returns {string}
 */
/**
 * Translation function for partners_title
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function partners_title(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'OUR PARTNERS';
	if (tag === 'fr') return 'NOS PARTENAIRES';
	return 'OUR PARTNERS';
}

/**
 * Translation function for footer_address
 * @returns {string}
 */
/**
 * Translation function for footer_address
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_address(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Address';
	if (tag === 'fr') return 'Adresse';
	return 'Address';
}

/**
 * Translation function for footer_complex
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_complex(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Dorval Aquatic & Sports Complex';
	if (tag === 'fr') return 'Complexe aquatique et sportif de Dorval';
	return 'Dorval Aquatic & Sports Complex';
}

/**
 * Translation function for footer_street
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_street(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return '1295 Dawson Avenue';
	if (tag === 'fr') return '1295, avenue Dawson';
	return '1295 Dawson Avenue';
}

/**
 * Translation function for footer_city
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_city(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Dorval, Quebec H9S 1Y3';
	if (tag === 'fr') return 'Dorval, Québec H9S 1Y3';
	return 'Dorval, Quebec H9S 1Y3';
}

/**
 * Translation function for footer_contact
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_contact(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Contact';
	if (tag === 'fr') return 'Contact';
	return 'Contact';
}

/**
 * Translation function for footer_phone
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_phone(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return '514-633-4209';
	if (tag === 'fr') return '514-633-4209';
	return '514-633-4209';
}

/**
 * Translation function for footer_email
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_email(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'info@swimdorval.ca';
	if (tag === 'fr') return 'info@swimdorval.ca';
	return 'info@swimdorval.ca';
}

/**
 * Translation function for footer_socialize
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_socialize(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'SOCIALIZE';
	if (tag === 'fr') return 'RÉSEAUX SOCIAUX';
	return 'SOCIALIZE';
}

/**
 * Translation function for footer_twitter
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_twitter(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return '@swimdorval';
	if (tag === 'fr') return '@swimdorval';
	return '@swimdorval';
}

/**
 * Translation function for footer_facebook
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_facebook(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'swimdorval';
	if (tag === 'fr') return 'swimdorval';
	return 'swimdorval';
}

/**
 * Translation function for footer_instagram
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_instagram(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'swimdorval';
	if (tag === 'fr') return 'swimdorval';
	return 'swimdorval';
}

/**
 * Translation function for footer_youtube
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_youtube(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'swimdorval';
	if (tag === 'fr') return 'swimdorval';
	return 'swimdorval';
}

/**
 * Translation function for footer_sponsors
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_sponsors(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'SPONSORS';
	if (tag === 'fr') return 'COMMANDITAIRES';
	return 'SPONSORS';
}

/**
 * Translation function for footer_copyright
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_copyright(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Copyright © 2025';
	if (tag === 'fr') return 'Droits d\'auteur © 2025';
	return 'Copyright © 2025';
}

/**
 * Translation function for footer_clubName
 * @param {import('./runtime.js').LanguageTag} [lang] - Optional language tag
 * @returns {string}
 */
export function footer_clubName(lang) {
	const tag = lang || getLanguageTag();
	if (tag === 'en') return 'Dorval Swim Club | All rights reserved.';
	if (tag === 'fr') return 'Club de natation Dorval | Tous droits réservés.';
	return 'Dorval Swim Club | All rights reserved.';
}

